"""add backtest snapshots table

Revision ID: 3cae25ba04d6
Revises: 83833177e10b
Create Date: 2026-09-17 00:26:28.114124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cae25ba04d6'
down_revision: Union[str, Sequence[str], None] = '83833177e10b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('experiment', sa.String(length=32), nullable=False),
    sa.Column('strategy_version', sa.String(length=64), nullable=False),
    sa.Column('n_bars', sa.Integer(), nullable=False),
    sa.Column('num_trades', sa.Integer(), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('sortino', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('exposure', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_snapshots_computed_at'), 'backtest_snapshots', ['computed_at'], unique=False)
    op.create_index(op.f('ix_backtest_snapshots_experiment'), 'backtest_snapshots', ['experiment'], unique=False)
    op.create_index(op.f('ix_backtest_snapshots_symbol'), 'backtest_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_backtest_snapshots_timeframe'), 'backtest_snapshots', ['timeframe'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backtest_snapshots_timeframe'), table_name='backtest_snapshots')
    op.drop_index(op.f('ix_backtest_snapshots_symbol'), table_name='backtest_snapshots')
    op.drop_index(op.f('ix_backtest_snapshots_experiment'), table_name='backtest_snapshots')
    op.drop_index(op.f('ix_backtest_snapshots_computed_at'), table_name='backtest_snapshots')
    op.drop_table('backtest_snapshots')
    # ### end Alembic commands ###
