"""initial schema: assets, candles, indicators, strategy_signals, agent_predictions, decisions

Revision ID: 74d7019c4c0f
Revises: 
Create Date: 2026-09-15 14:19:40.222930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d7019c4c0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange', name='uq_asset_symbol_exchange')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'timeframe', 'timestamp', name='uq_candle_asset_tf_ts')
    )
    op.create_index(op.f('ix_candles_asset_id'), 'candles', ['asset_id'], unique=False)
    op.create_index(op.f('ix_candles_timeframe'), 'candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_candles_timestamp'), 'candles', ['timestamp'], unique=False)
    op.create_table('indicator_ichimoku',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candle_id', sa.String(length=36), nullable=False),
    sa.Column('tenkan', sa.Float(), nullable=True),
    sa.Column('kijun', sa.Float(), nullable=True),
    sa.Column('senkou_a', sa.Float(), nullable=True),
    sa.Column('senkou_b', sa.Float(), nullable=True),
    sa.Column('cloud_top', sa.Float(), nullable=True),
    sa.Column('cloud_bot', sa.Float(), nullable=True),
    sa.Column('kumo_thickness', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('price_vs_kumo', sa.String(length=16), nullable=True),
    sa.Column('tk_cross', sa.String(length=16), nullable=True),
    sa.Column('tk_strength', sa.String(length=16), nullable=True),
    sa.Column('future_kumo', sa.String(length=16), nullable=True),
    sa.Column('chikou_state', sa.String(length=16), nullable=True),
    sa.Column('kumo_breakout', sa.String(length=16), nullable=True),
    sa.Column('trend_strength', sa.String(length=16), nullable=True),
    sa.Column('is_projected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candle_id'], ['candles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candle_id')
    )
    op.create_table('indicator_rvol',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candle_id', sa.String(length=36), nullable=False),
    sa.Column('rvol', sa.Float(), nullable=True),
    sa.Column('rvol5', sa.Float(), nullable=True),
    sa.Column('rvol10', sa.Float(), nullable=True),
    sa.Column('rvol20', sa.Float(), nullable=True),
    sa.Column('vol_accel', sa.Float(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('anomaly_level', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['candle_id'], ['candles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candle_id')
    )
    op.create_table('strategy_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candle_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('rvol', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candle_id'], ['candles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_signals_candle_id'), 'strategy_signals', ['candle_id'], unique=False)
    op.create_index(op.f('ix_strategy_signals_symbol'), 'strategy_signals', ['symbol'], unique=False)
    op.create_table('agent_predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('invalidation', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['strategy_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_predictions_signal_id'), 'agent_predictions', ['signal_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('agreement', sa.Float(), nullable=False),
    sa.Column('weights_used', sa.JSON(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('invalidation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['strategy_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_signal_id'), 'decisions', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_signal_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_agent_predictions_signal_id'), table_name='agent_predictions')
    op.drop_table('agent_predictions')
    op.drop_index(op.f('ix_strategy_signals_symbol'), table_name='strategy_signals')
    op.drop_index(op.f('ix_strategy_signals_candle_id'), table_name='strategy_signals')
    op.drop_table('strategy_signals')
    op.drop_table('indicator_rvol')
    op.drop_table('indicator_ichimoku')
    op.drop_index(op.f('ix_candles_timestamp'), table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe'), table_name='candles')
    op.drop_index(op.f('ix_candles_asset_id'), table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
