"""add paper_positions table

Revision ID: 83833177e10b
Revises: 74d7019c4c0f
Create Date: 2026-09-16 12:45:54.692231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83833177e10b'
down_revision: Union[str, Sequence[str], None] = '74d7019c4c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_decision', sa.String(length=16), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_positions_source'), 'paper_positions', ['source'], unique=False)
    op.create_index(op.f('ix_paper_positions_status'), 'paper_positions', ['status'], unique=False)
    op.create_index(op.f('ix_paper_positions_symbol'), 'paper_positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_paper_positions_user_id'), 'paper_positions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_positions_user_id'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_symbol'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_status'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_source'), table_name='paper_positions')
    op.drop_table('paper_positions')
    # ### end Alembic commands ###
